changesDir: .changes
unreleasedDir: unreleased
headerPath: header.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: "## [{{.VersionNoPrefix}}] - {{.Time.Format \"2006-01-02\"}}"
kindFormat: "### {{.Kind}}"
changeFormat: "- {{.Body}}"

kinds:
  - label: Added
    auto: minor
  - label: Changed
    auto: patch
  - label: Fixed
    auto: patch
  - label: Breaking Changes
    auto: minor   # treat as minor while major version is 0
  - label: Infrastructure
    auto: none    # tooling changes don't affect the version
  - label: Deprecated
    auto: patch
  - label: Removed
    auto: minor
  - label: Security
    auto: patch

newlines:
  afterChangelogHeader: 2
  afterVersion: 1

replacements:
  - path: setup.py
    find: 'version="[0-9]+\.[0-9]+\.[0-9]+"'
    replace: 'version="{{.VersionNoPrefix}}"'
    flags: ""
  - path: supertokens_python/constants.py
    find: 'VERSION = "[0-9]+\.[0-9]+\.[0-9]+"'
    replace: 'VERSION = "{{.VersionNoPrefix}}"'
    flags: ""
