REGISTER_OPTIONS_API = "/webauthn/options/register"

SIGNIN_OPTIONS_API = "/webauthn/options/signin"

SIGN_UP_API = "/webauthn/signup"

SIGN_IN_API = "/webauthn/signin"

GENERATE_RECOVER_ACCOUNT_TOKEN_API = "/user/webauthn/reset/token"

RECOVER_ACCOUNT_API = "/user/webauthn/reset"

SIGNUP_EMAIL_EXISTS_API = "/webauthn/email/exists"

# 60 seconds (60 * 1000ms)
DEFAULT_REGISTER_OPTIONS_TIMEOUT = 60000
DEFAULT_REGISTER_OPTIONS_ATTESTATION = "none"
DEFAULT_REGISTER_OPTIONS_RESIDENT_KEY = "required"
DEFAULT_REGISTER_OPTIONS_USER_VERIFICATION = "preferred"
DEFAULT_REGISTER_OPTIONS_USER_PRESENCE = True
# -8 = EdDSA, -7 = ES256, -257 = RS256
DEFAULT_REGISTER_OPTIONS_SUPPORTED_ALGORITHM_IDS = [-8, -7, -257]

# 60 seconds (60 * 1000ms)
DEFAULT_SIGNIN_OPTIONS_TIMEOUT = 60000
DEFAULT_SIGNIN_OPTIONS_USER_VERIFICATION = "preferred"
DEFAULT_SIGNIN_OPTIONS_USER_PRESENCE = True
