name: "Test Workflow"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  define-versions:
    runs-on: ubuntu-latest
    outputs:
      fdiVersions: ${{ steps.versions.outputs.fdiVersions }}
      cdiVersions: ${{ steps.versions.outputs.cdiVersions }}
      pyVersions: '["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]'
    steps:
      - uses: actions/checkout@v4
      - uses: supertokens/get-supported-versions-action@main
        id: versions
        with:
          has-fdi: true
          has-cdi: true

  test:
    runs-on: ubuntu-latest
    needs: define-versions
    strategy:
      fail-fast: false
      matrix:
        cdi-version: ${{ fromJSON(needs.define-versions.outputs.cdiVersions) }}
        fdi-version: ${{ fromJSON(needs.define-versions.outputs.fdiVersions) }}
    steps:
      - uses: supertokens/get-versions-action@main
        id: versions
        with:
          driver-name: python
          cdi-version: ${{ matrix.cdi-version }}
          fdi-version: ${{ matrix.fdi-version }}
        env:
          SUPERTOKENS_API_KEY: ${{ secrets.SUPERTOKENS_API_KEY }}
